# Generated by Django 5.0.4 on 2024-04-15 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_rename_answers_answer_chosen_answer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="survey",
            old_name="age",
            new_name="age_group",
        ),
    ]
